name: Bug
description: Report a regression or broken behavior.
labels:
  - type:bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What broke and why it matters.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact UI steps if applicable.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/screenshots
      description: Include console output or screenshots if available.
