name: Feature
description: New product or workflow capability.
labels:
  - type:feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user need or pain does this address?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the solution at a high level.
    validations:
      required: true
  - type: textarea
    id: ux
    attributes:
      label: UX notes
      description: Any UI/UX expectations, mocks, or copy.
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
